# Generated by Django 4.1.3 on 2023-01-23 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_name_venue_venue_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='venue_name',
            new_name='name',
        ),
    ]
