# Generated by Django 4.1.5 on 2023-01-28 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='approved',
        ),
    ]
