# Generated by Django 4.1.5 on 2023-02-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='event_types',
            field=models.TextField(blank=True),
        ),
    ]
